spring.datasource.url=jdbc:mysql://localhost:3306/usersdb
spring.datasource.username=root
spring.datasource.password=tailx0913
spring.jpa.hibernate.ddl-auto=update
#hi?n th? các câu l?nh trong c?a s? conshole
spring.jpa.properties.hibernate.show_sql=true